@Chatbot.Api_HostAddress = http://localhost:5024

### Đăng nhập Admin lấy Access Token
# @name login
POST {{Chatbot.Api_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@chatbot.local",
  "password": "Admin_Dev_P@ssw0rd1"
}

### Gửi mã xác nhận Gmail (Yêu cầu quyền Admin)
# Thay đổi số '2' bằng ID của User cần kích hoạt
POST {{Chatbot.Api_HostAddress}}/api/v1/admin/users/2/send-confirmation-email
Authorization: Bearer {{login.response.body.accessToken}}

### Xác nhận mã OTP kích hoạt tài khoản (Không yêu cầu đăng nhập)
POST {{Chatbot.Api_HostAddress}}/api/v1/admin/users/confirm-email
Content-Type: application/json

{
  "email": "student@chatbot.local",
  "code": "123456"
}
