// <auto-generated />
using System;
using Chatbot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatbot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    [Migration("20260616074401_AddSubjectInstructor")]
    partial class AddSubjectInstructor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chatbot.Domain.Entities.AppSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppSetting_Key");

                    b.ToTable("AppSetting", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("IX_AuditLog_ActorUserId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLog_CreatedAtUtc");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_AuditLog_TargetUserId");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_AuditLog_Target");

                    b.ToTable("AuditLog", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_NewValues_Json", "[NewValues] IS NULL OR ISJSON([NewValues]) = 1");

                            t.HasCheckConstraint("CK_AuditLog_OldValues_Json", "[OldValues] IS NULL OR ISJSON([OldValues]) = 1");
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Chapter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Vietnamese_100_CI_AI");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Chapter_SubjectId");

                    b.ToTable("Chapter", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("EmbeddingModelId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<long?>("LlmModelId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddingModelId");

                    b.HasIndex("LlmModelId");

                    b.HasIndex("SessionId", "CreatedAtUtc")
                        .HasDatabaseName("IX_ChatMessage_SessionId_CreatedAtUtc");

                    b.ToTable("ChatMessage", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChatSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("PinnedChunkingStrategyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PinnedEmbeddingModelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PinnedLlmModelId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PinnedChunkingStrategyId");

                    b.HasIndex("PinnedEmbeddingModelId");

                    b.HasIndex("PinnedLlmModelId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_ChatSession_SubjectId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ChatSession_UserId");

                    b.ToTable("ChatSession", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChunkEmbedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChunkId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<long>("EmbeddingModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IndexedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VectorCollection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("VectorPointId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddingModelId")
                        .HasDatabaseName("IX_ChunkEmbedding_Model");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("EmbeddingModelId"), new[] { "ChunkId", "VectorCollection", "VectorPointId", "Status" });

                    b.HasIndex("ChunkId", "EmbeddingModelId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChunkEmbedding_Chunk_Model");

                    b.HasIndex("VectorCollection", "VectorPointId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChunkEmbedding_PointId");

                    b.ToTable("ChunkEmbedding", "rag");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChunkingStrategy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int?>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChunkingStrategy_Name");

                    b.ToTable("ChunkingStrategy", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_ChunkingStrategy_Params_Json", "[Params] IS NULL OR ISJSON([Params]) = 1");
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("IndexedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sha256Checksum")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("LocalDisk");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Vietnamese_100_CI_AI");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("IX_Document_ChapterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Document_Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Document_SubjectId");

                    b.HasIndex("SubjectId", "Sha256Checksum")
                        .IsUnique()
                        .HasDatabaseName("UQ_Document_Subject_Sha")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Document", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<long>("ChunkingStrategyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChunkingStrategyId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_Chunk_DocumentId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DocumentId"), new[] { "ChunkingStrategyId", "ChunkIndex" });

                    b.HasIndex("DocumentId", "ChunkingStrategyId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_DocumentChunk_Doc_Strategy_Index");

                    b.ToTable("DocumentChunk", "rag", t =>
                        {
                            t.HasCheckConstraint("CK_DocumentChunk_Metadata_Json", "[Metadata] IS NULL OR ISJSON([Metadata]) = 1");
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.DocumentProcessingJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<long?>("ChunkingStrategyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EmbeddingModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkingStrategyId");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_DocProcJob_ActivePerDoc")
                        .HasFilter("[State] IN ('queued','running')");

                    b.HasIndex("EmbeddingModelId");

                    b.ToTable("DocumentProcessingJob", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.EmbeddingModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxInputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QdrantCollectionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_EmbeddingModel_Name");

                    b.HasIndex("QdrantCollectionName")
                        .IsUnique()
                        .HasDatabaseName("UQ_EmbeddingModel_Collection");

                    b.ToTable("EmbeddingModel", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.EvaluationResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AnswerCorrectness")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("AnswerRelevancy")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("ContextPrecision")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("ContextRecall")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("ExperimentRunId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Faithfulness")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<string>("GeneratedAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("PerQuestionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RetrievedContexts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TestQuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentRunId")
                        .HasDatabaseName("IX_EvaluationResult_RunId");

                    b.HasIndex("TestQuestionId");

                    b.HasIndex("ExperimentRunId", "TestQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EvaluationResult_Run_Question");

                    b.ToTable("EvaluationResult", "rbl", t =>
                        {
                            t.HasCheckConstraint("CK_Eval_AnsCorr", "[AnswerCorrectness] IS NULL OR [AnswerCorrectness] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_Eval_AnsRel", "[AnswerRelevancy] IS NULL OR [AnswerRelevancy] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_Eval_Contexts_Json", "[RetrievedContexts] IS NULL OR ISJSON([RetrievedContexts]) = 1");

                            t.HasCheckConstraint("CK_Eval_CtxPrec", "[ContextPrecision] IS NULL OR [ContextPrecision] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_Eval_CtxRec", "[ContextRecall] IS NULL OR [ContextRecall] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_Eval_Faith", "[Faithfulness] IS NULL OR [Faithfulness] BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.EvaluationRetrieval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChunkId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("EvaluationResultId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<string>("Snippet")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationResultId")
                        .HasDatabaseName("IX_EvaluationRetrieval_ResultId");

                    b.ToTable("EvaluationRetrieval", "rbl");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Experiment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Experiment", "rbl");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ExperimentRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChunkingStrategyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConfigSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorpusSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("EmbeddingModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExperimentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExperimentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("LlmModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("RunName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChunkingStrategyId");

                    b.HasIndex("EmbeddingModelId");

                    b.HasIndex("ExperimentId")
                        .HasDatabaseName("IX_ExperimentRun_ExperimentId");

                    b.HasIndex("LlmModelId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ExperimentRun_Status")
                        .HasFilter("[Status] IN ('queued','running')");

                    b.ToTable("ExperimentRun", "rbl", t =>
                        {
                            t.HasCheckConstraint("CK_Run_ConfigSnapshot_Json", "[ConfigSnapshot] IS NULL OR ISJSON([ConfigSnapshot]) = 1");

                            t.HasCheckConstraint("CK_Run_CorpusSnapshot_Json", "[CorpusSnapshot] IS NULL OR ISJSON([CorpusSnapshot]) = 1");

                            t.HasCheckConstraint("CK_Run_Params_Json", "[Params] IS NULL OR ISJSON([Params]) = 1");

                            t.HasCheckConstraint("CK_Run_TypeModel", "([ExperimentType] = 'embedding_bench' AND [EmbeddingModelId] IS NOT NULL) OR ([ExperimentType] = 'chunking_bench' AND [ChunkingStrategyId] IS NOT NULL) OR ([ExperimentType] = 'rag_vs_finetune' AND [LlmModelId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ExperimentRunMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AvgAnswerCorrectness")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("AvgAnswerRelevancy")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("AvgContextPrecision")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("AvgContextRecall")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("AvgFaithfulness")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<decimal?>("AvgLatencyMs")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long>("ExperimentRunId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentRunId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExperimentRunMetric_RunId");

                    b.ToTable("ExperimentRunMetric", "rbl");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.IntegrationOutbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AvailableAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Outbox_Pending")
                        .HasFilter("[Status] = 'pending'");

                    b.ToTable("IntegrationOutbox", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Outbox_Payload_Json", "[Payload] IS NULL OR ISJSON([Payload]) = 1");
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.LlmModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseModel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_LlmModel_Name");

                    b.ToTable("LlmModel", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.MessageCitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChunkId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentTitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("RelevanceScore")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<string>("Snippet")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("IX_MessageCitation_MessageId");

                    b.ToTable("MessageCitation", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_PasswordResetToken_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetToken", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permission_Code");

                    b.ToTable("Permission", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_RefreshToken_FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshToken_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshToken_UserId");

                    b.ToTable("RefreshToken", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Role_NormalizedName");

                    b.ToTable("Role", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermission_PermissionId");

                    b.ToTable("RolePermission", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Vietnamese_100_CI_AI");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Subject_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Subject", "dbo");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.SubjectInstructor", b =>
                {
                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("AssignedBy")
                        .HasColumnType("bigint");

                    b.HasKey("SubjectId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SubjectInstructor_UserId");

                    b.ToTable("SubjectInstructor", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessTokenMinutes")
                        .HasColumnType("int");

                    b.Property<long?>("ActiveChunkingStrategyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActiveEmbeddingModelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActiveLlmModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("HistoryWindowTurns")
                        .HasColumnType("int");

                    b.Property<int>("LockoutMaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("LockoutMinutes")
                        .HasColumnType("int");

                    b.Property<long>("MaxUploadBytes")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MinRelevanceScore")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal(7,6)");

                    b.Property<string>("PromptTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefreshTokenDays")
                        .HasColumnType("int");

                    b.Property<int>("RetrievalTopK")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("ScopeRestriction")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActiveChunkingStrategyId");

                    b.HasIndex("ActiveEmbeddingModelId");

                    b.HasIndex("ActiveLlmModelId");

                    b.ToTable("SystemConfiguration", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_SystemConfiguration_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.TestQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GroundTruth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_TestQuestion_SubjectId");

                    b.ToTable("TestQuestion", "rbl");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_NormalizedEmail")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("User", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("AssignedBy")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRole_RoleId");

                    b.ToTable("UserRole", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.UserSubject", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "SubjectId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_UserSubject_SubjectId");

                    b.ToTable("UserSubject", "auth");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.EmbeddingModel", null)
                        .WithMany()
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.LlmModel", null)
                        .WithMany()
                        .HasForeignKey("LlmModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ChunkingStrategy", null)
                        .WithMany()
                        .HasForeignKey("PinnedChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.EmbeddingModel", null)
                        .WithMany()
                        .HasForeignKey("PinnedEmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.LlmModel", null)
                        .WithMany()
                        .HasForeignKey("PinnedLlmModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChunkEmbedding", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.DocumentChunk", "Chunk")
                        .WithMany("Embeddings")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.EmbeddingModel", "EmbeddingModel")
                        .WithMany()
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("EmbeddingModel");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Document", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Domain.Entities.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ChunkingStrategy", "ChunkingStrategy")
                        .WithMany()
                        .HasForeignKey("ChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChunkingStrategy");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.DocumentProcessingJob", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ChunkingStrategy", null)
                        .WithMany()
                        .HasForeignKey("ChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.Document", "Document")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.EmbeddingModel", null)
                        .WithMany()
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.EvaluationResult", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ExperimentRun", "ExperimentRun")
                        .WithMany("Results")
                        .HasForeignKey("ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.TestQuestion", "TestQuestion")
                        .WithMany()
                        .HasForeignKey("TestQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExperimentRun");

                    b.Navigation("TestQuestion");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.EvaluationRetrieval", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.EvaluationResult", "EvaluationResult")
                        .WithMany("Retrievals")
                        .HasForeignKey("EvaluationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationResult");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Experiment", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ExperimentRun", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ChunkingStrategy", "ChunkingStrategy")
                        .WithMany()
                        .HasForeignKey("ChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.EmbeddingModel", "EmbeddingModel")
                        .WithMany()
                        .HasForeignKey("EmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.Experiment", "Experiment")
                        .WithMany("Runs")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.LlmModel", "LlmModel")
                        .WithMany()
                        .HasForeignKey("LlmModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChunkingStrategy");

                    b.Navigation("EmbeddingModel");

                    b.Navigation("Experiment");

                    b.Navigation("LlmModel");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ExperimentRunMetric", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ExperimentRun", "ExperimentRun")
                        .WithOne("Metric")
                        .HasForeignKey("Chatbot.Domain.Entities.ExperimentRunMetric", "ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperimentRun");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.MessageCitation", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ChatMessage", "Message")
                        .WithMany("Citations")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.SubjectInstructor", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Subject", "Subject")
                        .WithMany("Instructors")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.SystemConfiguration", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.ChunkingStrategy", "ActiveChunkingStrategy")
                        .WithMany()
                        .HasForeignKey("ActiveChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.EmbeddingModel", "ActiveEmbeddingModel")
                        .WithMany()
                        .HasForeignKey("ActiveEmbeddingModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Domain.Entities.LlmModel", "ActiveLlmModel")
                        .WithMany()
                        .HasForeignKey("ActiveLlmModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveChunkingStrategy");

                    b.Navigation("ActiveEmbeddingModel");

                    b.Navigation("ActiveLlmModel");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.TestQuestion", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.UserSubject", b =>
                {
                    b.HasOne("Chatbot.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chatbot.Domain.Entities.User", "User")
                        .WithMany("UserSubjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChatMessage", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("ProcessingJobs");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.DocumentChunk", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.EvaluationResult", b =>
                {
                    b.Navigation("Retrievals");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Experiment", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.ExperimentRun", b =>
                {
                    b.Navigation("Metric");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Documents");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Chatbot.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
